name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: test 
        run: npm test
      - name: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: pushing code to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "keith-pokedex" #Must be unique in Heroku
          heroku_email: "keithlow98@gmail.com"
          procfile: "web: npm run start-prod"
          healthcheck: "https://keith-pokedex.herokuapp.com/health"
          rollbackonhealthcheckfailed: true

      - uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - uses: 8398a7/action-slack@v3.9.1
      # - name: send success notification to slack
        with:
          status: ${{ job.status }}
          fields: commit, author, took
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') && success() }}  

      - uses: 8398a7/action-slack@v3.9.1
      # - name: send failure notification to slack
        with: 
          status: ${{ job.status }}
          fields: all
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') && failure() }}
